[build]
  command = "parcel build index.html && mkdir dist/.well-known && echo $APPLE_DEVELOPER_MERCHANTID_DOMAIN_ASSOCIATION > dist/.well-known/apple-developer-merchantid-domain-association"

[dev]
  command = "parcel index.html"
